### ISSUE TITLE
Add page to document "Respect Copyright"

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#18]
See https://github.com/OpenLiveWriter/OpenLiveWriter.Github.io/issues/17 and https://github.com/OpenLiveWriter/OpenLiveWriter/issues/182

Clicking on "Please respect copyright" navigates to http://openlivewriter.org/WriterRedirect/Copyright in the browser, and gives a 404 File Not Found error,

Note that LiveWriter referred users to a Microsoft legal documentation website.

**Comment by kathweaver** [comment]
<img width="367" alt="085c6dda-a5df-11e5-81db-f204f41c94d6" src="https://cloud.githubusercontent.com/assets/7053084/11921355/12687b56-a74d-11e5-998d-3d5f10038550.png">

**Comment by RobStand** [comment]
It may be preferable to remove the link instead of creating a new legal page. @martinwoodward what do you think?

**Comment by kathweaver** [comment]
I've been looking at the code and am thinking that it might be required:

In MediaInsertForm.cs

  if (!showCopyright || !MarketizationOptions.IsFeatureEnabled(MarketizationOptions.Feature.VideoCopyright))
            {
                copyrightLinkLabel.Visible = false;
            }
            else
            {
                copyrightLinkLabel.Font = Res.GetFont(FontSize.Small, FontStyle.Regular);
                copyrightLinkLabel.Text = Res.Get(StringId.Plugin_Video_Copyright_Notice);
                string link = MarketizationOptions.GetFeatureParameter(MarketizationOptions.Feature.VideoCopyright, "Glink");
                if (link == null || link == String.Empty)
                    copyrightLinkLabel.LinkArea = new LinkArea(0, 0);
                else
                    copyrightLinkLabel.LinkClicked += copyrightLinkLabel_LinkClicked;
            }

**Comment by martinwoodward** [comment]
I think updating the application itself so that it links to http://www.youtube.com/t/community_guidelines rather than a OLW page is probably the best way to ensure we are encouraging users of YouTube to use their service correctly.

In the old days of Live Writer being a Microsoft product, we'd always have used a redirection service rather than embed links to external services as external services can always change links as so it would have given us a way to update the link without updating the application.  In OLW as we can update the application so easily I'm less worried about that.

Therefore, maybe we should just update the YouTube links to point to the relevant pages on the YouTube site if we can find them or their community guidelines page if we cannot find a modern equivalent?

See https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/intl/markets/master.xml#L19-L23

**Comment by kathweaver** [comment]
Close with pull request #23
